---
- name: Add repo/gpgkey
  script: kube_repo.sh
  
- name: SELINUX setenforce 0
  selinux:
    state: disabled

-   name: Install Kube
    yum: name={{ item }} state=present
    with_items:
      - kubelet
      - kubeadm
      - kubectl

- name: Enable Kubelet service
  systemd:
    name: kubelet
    enabled: yes
    state: started
